discord:
  token: your_token
  discordChannelId: channel_id
  minecraftPrefix: some_prefix
  webhook: some_webhook
irc:
  username: irc_username
  hostname: irc_hostname
  port: irc_port
  tls: is_tls_enabled
  timeout: connection_timeout
  channel: irc_channel