name: ChatBridge
version: '${version}'
main: xyz.crafttogether.chatbridge.ChatBridge
api-version: 1.18
depend:
  - Kelp
  - Rinku
  - Weg
commands:
  irc:
    description: commands related to the IRC connection
    usage: /<command> <subcommand>
